build:
  version: "v3"

accounts:
  message: "Welcome to EazyBank Accounts Microservice REST API"
  contactDetails:
    name: "Dipesh B C"
    email: "bcdipeshwork@gmail.com"
  onCallSupport:
      - "(555) 555-1234"
      - "(555) 555-5678"