build:
  version: "v2"

accounts:
  message: "Welcome to EazyBank Accounts Microservice QA environment REST API"
  contactDetails:
    name: "John Doe"
    email: "johndoe@gmail.com"
  onCallSupport:
      - "(666) 555-1234"
      - "(666) 555-5678"