build:
  version: "v1"

accounts:
  message: "Welcome to EazyBank Accounts Microservice Production environment REST API"
  contactDetails:
    name: "Jane Doe"
    email: "janedoe@gmail.com"
  onCallSupport:
      - "(777) 555-1234"
      - "(777) 555-5678"