build:
  version: "v2"

cards:
  message: "Welcome to EazyBank Cards Microservice production environment REST API"
  contactDetails:
    name: "Jane Doe"
    email: "janedoe@gmail.com"
  onCallSupport:
    - "(777) 555-1234"
    - "(777) 555-5678"