services:
  #########################################################################
  # 🔗 Base network membership
  #########################################################################
  network-deploy-service:
    networks:
      - eazybank-network

  #########################################################################
  # 🗄️ MySQL base for microservice DBs
  #########################################################################
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  #########################################################################
  # ☕ Java microservice base (OpenTelemetry to Tempo)
  #########################################################################
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      # Auto-instrumentation
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"

      # Send traces to Tempo (Host A)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318

      # Disable agent-side metrics/logs (Prometheus + Loki handle these)
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  #########################################################################
  # 📦 ConfigServer-aware base (for Spring apps)
  #########################################################################
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  #########################################################################
  # 🧭 Eureka-aware base (adds discovery)
  #########################################################################
  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  eazybank-network:
    external: true
